# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1STLkQnHjhvQSZ6g7HLBtirn0YDuuB34T
"""

import numpy as np
x = np.array([[1],[2],[3],[4],[5]])
y = np.array([6,7,8,9,10])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)


from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
print(x_test)
#test = np.array([[14],[16]])

pred_y = model.predict(x_test)
print(pred_y)

#define dataset
import numpy as np

x = np.array([[1],[2],[3],[4],[5]])
y = np.array([6,7,8,9,10])

#model import
from sklearn.linear_model import LinearRegression

#assign variable
model = LinearRegression()

#model.fit #for training
model.fit(x,y)

#prediction
test = np.array([[12],[13]])
pred_y = model.predict(test)
print(pred_y)